# Paleta de Colores
$blue = rgb(4097ff)
$red = rgb(f38ba8)
$white = rgb(fff)
$yellow = rgb(f9e2af)
$black = rgb(000)

# Thema/Icons/Font/Cursor
$font = 3270 Nerd Font Mono
$theme = Layan-Dark
$icons = breeze-dark
$cursor = Nordic-cursors

# Programs
$terminal = kitty
$fileManager = kitty ranger
$menu = wofi --show drun
$navegador = brave
$ide = code
$search = io.github.cboxdoerfer.FSearch

# Especial
$mainMod = SUPER
