# Default
windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}
windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# Etiquetas
windowrule = match:class ^(thunar)$, tag +opacity
windowrule = match:class ^(org.telegram.desktop)$, tag +redes
windowrule = match:class ^(discord)$, tag +redes
windowrule = match:class ^(brave-browser)$, tag +opacity
windowrule = match:class ^(code)$, tag +ide
windowrule = match:class ^(jetbrains-studio)$, tag +ide
windowrule = match:class ^(org.gnome.Rhythmbox3)$, tag +opacity
windowrule = match:class ^(vlc)$, tag +reproductor
windowrule = match:class ^(mpv)$, tag +reproductor
windowrule = match:class ^(protonvpn-app)$, tag +utility
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, tag +utility
windowrule = match:class ^(blueman-manager)$, tag +utility
windowrule = match:class ^(protonvpn-ap)$, tag +utility
windowrule = match:class ^(fsearch)$, tag +utility
windowrule = match:class ^(hyprpolkitagent)$, tag +opacity

# Reglas
windowrule = match:tag opacity, opacity 0.8
windowrule {
    name = Reproductor
    match:tag = reproductor
    float = on
    center = on
}
windowrule{
    name = Redes
    match:tag = redes
    float = on
    opacity = 0.8
}
windowrule {
    name = Editores
    match:tag = ide
    opacity = 0.8
    monitor = DP-1
}
windowrule {
    name = Utilities
    match:tag = utility
    float = on
    center = on
    opacity = 0.8
}

# Especificas

windowrule {
    name = Conky
    match:class = ^(Conky)$
    float = on
    monitor = DP-1
    no_initial_focus = on
}
windowrule {
    name = Thunar-Progress-bar
    match:class = ^(thunar)$
    match:title = ^(File Operation Progress)$
    float = on
    center = on
    size = (monitor_w*0.26) (monitor_h*0.18)
}
windowrule {
    name = Dust notifications
    match:class = ^(dust)$
    float = on
    monitor = DP-1
    opacity = 0.8
}
