# Auth agent
exec-once = systemctl --user start hyprpolkitagent
# NetworkManager
exec-once = nm-applet
# Notifications
exec-once = dunst -conf /home/azure/.config/dunst/dunstrc

# Hyprland
exec-once = waybar & hyprpaper &
exec-once = hypridle &

# Programs
exec-once = kitty
exec-once = Telegram

# Cliphboard
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
