exec-once = systemctl --user start hyprpolkitagent
exec-once = dunst -conf /home/azure/.config/dunst/dunstrc
exec-once = waybar & hypridle &
exec-once = hyprpaper &

# Cliphboard
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
