# Auth agent
exec-once = systemctl --user start hyprpolkitagent
# NetworkManager
exec-once = nm-applet
# Notifications
exec-once = dunst -conf /home/azure/.config/dunst/dunstrc

# Hyprland
exec-once = waybar & 
exec-once = hyprpaper &
exec-once = hypridle &

# Programs
exec-once = kitty tty-clock -c -C 4
exec-once = kitty
exec-once = kitty cava
exec-once = kitty ranger

# Cliphboard
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
