preload = ~/Pictures/fairy_tail_5.jpg
preload = ~/Pictures/fairy_tail_6.jpg

wallpaper {
    monitor = DP-1
    path = ~/Pictures/fairy_tail_5.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-2
    path = ~/Pictures/fairy_tail_6.jpg
    fit_mode = cover
}
