[Theme]
   style=Adwaita-dark
   icon_theme=Tela dracula dark
   font=0xProtoNerdFont
   font_size=11
   color_scheme=
   
[Misc]
   menus_have_icons=true
   single_click_activate=true
   shortcuts_for_context_menus=true
