wallpaper {
    monitor = DP-1
    path = $HOME/.wallpapers/anime girl 18.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-2
    path = $HOME/.wallpapers/miku 6.jpg
    fit_mode = cover
}
