## Hyprland Config

# Window and theme
source = ~/.config/hypr/theme.conf
source = ~/.config/hypr/config.conf

# Keybind
source = ~/.config/hypr/keybind.conf

# Autostart
source = ~/.config/hypr/autostart.conf

# Rule
source = ~/.config/hypr/window_rule.conf

ecosystem:no_update_news = true