[Theme]
   style=kvantum-dark
   icon_theme=Adwaita
   font=Sans Serif
   font_size=11
   color_scheme=
   
[Misc]
   menus_have_icons=true
   single_click_activate=true
   shortcuts_for_context_menus=true
