# Default
windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}
windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# Etiquetas
windowrule = match:class ^(kitty)$, tag +common
windowrule = match:class ^(thunar)$, tag +common
windowrule = match:class ^(org.telegram.desktop)$, tag +common
windowrule = match:class ^(discord)$, tag +common
windowrule = match:class ^(code)$, tag +code
windowrule = match:class ^(jetbrains-studio)$, tag +code
windowrule = match:class ^(org.xfce.mousepad)$, tag +code
windowrule = match:class ^(org.gnome.Rhythmbox3)$, tag +common
windowrule = match:class ^(mpv)$, tag +video
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, tag +common
windowrule = match:class ^(blueman-manager)$, tag +common
windowrule = match:class ^(protonvpn-app)$, tag +common
windowrule = match:class ^(fsearch)$, tag +common
windowrule = match:class ^(org.xfce.ristretto)$, tag +common
windowrule = match:class ^(xdm-app)$, tag +common
windowrule = match:class ^(brave-browser)$, tag +browser
windowrule = match:class ^(net.lutris.Lutris)$, tag +game

# Reglas
windowrule{
	name = Browser
	match:tag = browser
	monitor = 0
}
windowrule{
	name = Code
	match:tag = code
	monitor = 1
}
windowrule{
	name = Video
	match:tag = video
	fullscreen = on
	monitor = 1
	float = on
}
windowrule{
	name = Common
	match:tag = common
	monitor = 0

}
windowrule{
	name = Games
	match:tag = game
	monitor = 1
}
windowrule {
    name = Thunar-Progress-bar
    match:class = ^(thunar)$
    center = on
    size = (monitor_w*0.26) (monitor_h*0.18)
}
